import json

data = [
    {"path":"/workspace/.gitignore","diff":["@@ -0,0 +1,7 @@"]},
    {"path":"/workspace/CLAW.md","diff":["@@ -0,0 +1,21 @@"]},
    {"path":"/workspace/PARITY.md","diff":["@@ -0,0 +1,214 @@"]},
    {"path":"/workspace/README.md","diff":["@@ -1 +1,228 @@"]},
    {"path":"/workspace/assets/clawd-hero.jpeg","diff":[]},
    {"path":"/workspace/assets/instructkr.png","diff":[]},
    {"path":"/workspace/assets/omx/omx-readme-review-1.png","diff":[]},
    {"path":"/workspace/assets/omx/omx-readme-review-2.png","diff":[]},
    {"path":"/workspace/assets/star-history.png","diff":[]},
    {"path":"/workspace/assets/tweet-screenshot.png","diff":[]},
    {"path":"/workspace/assets/wsj-feature.png","diff":[]},
    {"path":"/workspace/rust/.github/workflows/ci.yml","diff":["@@ -0,0 +1,36 @@"]},
    {"path":"/workspace/rust/.gitignore","diff":["@@ -0,0 +1,3 @@"]},
    {"path":"/workspace/rust/CONTRIBUTING.md","diff":["@@ -0,0 +1,43 @@"]},
    {"path":"/workspace/rust/Cargo.lock","diff":["@@ -0,0 +1,2363 @@"]},
    {"path":"/workspace/rust/Cargo.toml","diff":["@@ -0,0 +1,23 @@"]},
    {"path":"/workspace/rust/README.md","diff":["@@ -0,0 +1,122 @@"]},
    {"path":"/workspace/rust/crates/api/Cargo.toml","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/rust/crates/api/src/client.rs","diff":["@@ -0,0 +1,141 @@"]},
    {"path":"/workspace/rust/crates/api/src/error.rs","diff":["@@ -0,0 +1,135 @@"]},
    {"path":"/workspace/rust/crates/api/src/lib.rs","diff":["@@ -0,0 +1,23 @@"]},
    {"path":"/workspace/rust/crates/api/src/providers/claw_provider.rs","diff":["@@ -0,0 +1,1046 @@"]},
    {"path":"/workspace/rust/crates/api/src/providers/mod.rs","diff":["@@ -0,0 +1,239 @@"]},
    {"path":"/workspace/rust/crates/api/src/providers/openai_compat.rs","diff":["@@ -0,0 +1,1050 @@"]},
    {"path":"/workspace/rust/crates/api/src/sse.rs","diff":["@@ -0,0 +1,279 @@"]},
    {"path":"/workspace/rust/crates/api/src/types.rs","diff":["@@ -0,0 +1,223 @@"]},
    {"path":"/workspace/rust/crates/api/tests/client_integration.rs","diff":["@@ -0,0 +1,483 @@"]},
    {"path":"/workspace/rust/crates/api/tests/openai_compat_integration.rs","diff":["@@ -0,0 +1,415 @@"]},
    {"path":"/workspace/rust/crates/api/tests/provider_client_integration.rs","diff":["@@ -0,0 +1,86 @@"]},
    {"path":"/workspace/rust/crates/claw-cli/Cargo.toml","diff":["@@ -0,0 +1,27 @@"]},
    {"path":"/workspace/rust/crates/claw-cli/src/app.rs","diff":["@@ -0,0 +1,402 @@"]},
    {"path":"/workspace/rust/crates/claw-cli/src/args.rs","diff":["@@ -0,0 +1,104 @@"]},
    {"path":"/workspace/rust/crates/claw-cli/src/init.rs","diff":["@@ -0,0 +1,432 @@"]},
    {"path":"/workspace/rust/crates/claw-cli/src/input.rs","diff":["@@ -0,0 +1,1195 @@"]},
    {"path":"/workspace/rust/crates/claw-cli/src/main.rs","diff":["@@ -0,0 +1,5090 @@"]},
    {"path":"/workspace/rust/crates/claw-cli/src/render.rs","diff":["@@ -0,0 +1,797 @@"]},
    {"path":"/workspace/rust/crates/commands/Cargo.toml","diff":["@@ -0,0 +1,14 @@"]},
    {"path":"/workspace/rust/crates/commands/src/lib.rs","diff":["@@ -0,0 +1,2667 @@"]},
    {"path":"/workspace/rust/crates/compat-harness/Cargo.toml","diff":["@@ -0,0 +1,14 @@"]},
    {"path":"/workspace/rust/crates/compat-harness/src/lib.rs","diff":["@@ -0,0 +1,356 @@"]},
    {"path":"/workspace/rust/crates/lsp/Cargo.toml","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/rust/crates/lsp/src/client.rs","diff":["@@ -0,0 +1,463 @@"]},
    {"path":"/workspace/rust/crates/lsp/src/error.rs","diff":["@@ -0,0 +1,62 @@"]},
    {"path":"/workspace/rust/crates/lsp/src/lib.rs","diff":["@@ -0,0 +1,283 @@"]},
    {"path":"/workspace/rust/crates/lsp/src/manager.rs","diff":["@@ -0,0 +1,191 @@"]},
    {"path":"/workspace/rust/crates/lsp/src/types.rs","diff":["@@ -0,0 +1,186 @@"]},
    {"path":"/workspace/rust/crates/plugins/Cargo.toml","diff":["@@ -0,0 +1,13 @@"]},
    {"path":"/workspace/rust/crates/plugins/bundled/example-bundled/.claw-plugin/plugin.json","diff":["@@ -0,0 +1,10 @@"]},
    {"path":"/workspace/rust/crates/plugins/bundled/example-bundled/hooks/post.sh","diff":["@@ -0,0 +1,2 @@"]},
    {"path":"/workspace/rust/crates/plugins/bundled/example-bundled/hooks/pre.sh","diff":["@@ -0,0 +1,2 @@"]},
    {"path":"/workspace/rust/crates/plugins/bundled/sample-hooks/.claw-plugin/plugin.json","diff":["@@ -0,0 +1,10 @@"]},
    {"path":"/workspace/rust/crates/plugins/bundled/sample-hooks/hooks/post.sh","diff":["@@ -0,0 +1,2 @@"]},
    {"path":"/workspace/rust/crates/plugins/bundled/sample-hooks/hooks/pre.sh","diff":["@@ -0,0 +1,2 @@"]},
    {"path":"/workspace/rust/crates/plugins/src/hooks.rs","diff":["@@ -0,0 +1,395 @@"]},
    {"path":"/workspace/rust/crates/plugins/src/lib.rs","diff":["@@ -0,0 +1,2943 @@"]},
    {"path":"/workspace/rust/crates/runtime/Cargo.toml","diff":["@@ -0,0 +1,20 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/bash.rs","diff":["@@ -0,0 +1,283 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/bootstrap.rs","diff":["@@ -0,0 +1,56 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/compact.rs","diff":["@@ -0,0 +1,702 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/config.rs","diff":["@@ -0,0 +1,1294 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/conversation.rs","diff":["@@ -0,0 +1,801 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/file_ops.rs","diff":["@@ -0,0 +1,550 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/hooks.rs","diff":["@@ -0,0 +1,357 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/json.rs","diff":["@@ -0,0 +1,358 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/lib.rs","diff":["@@ -0,0 +1,94 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/mcp.rs","diff":["@@ -0,0 +1,300 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/mcp_client.rs","diff":["@@ -0,0 +1,234 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/mcp_stdio.rs","diff":["@@ -0,0 +1,1720 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/oauth.rs","diff":["@@ -0,0 +1,589 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/permissions.rs","diff":["@@ -0,0 +1,232 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/prompt.rs","diff":["@@ -0,0 +1,795 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/remote.rs","diff":["@@ -0,0 +1,401 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/sandbox.rs","diff":["@@ -0,0 +1,364 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/session.rs","diff":["@@ -0,0 +1,436 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/sse.rs","diff":["@@ -0,0 +1,128 @@"]},
    {"path":"/workspace/rust/crates/runtime/src/usage.rs","diff":["@@ -0,0 +1,310 @@"]},
    {"path":"/workspace/rust/crates/server/Cargo.toml","diff":["@@ -0,0 +1,20 @@"]},
    {"path":"/workspace/rust/crates/server/src/lib.rs","diff":["@@ -0,0 +1,442 @@"]},
    {"path":"/workspace/rust/crates/tools/.gitignore","diff":["@@ -0,0 +1 @@"]},
    {"path":"/workspace/rust/crates/tools/Cargo.toml","diff":["@@ -0,0 +1,18 @@"]},
    {"path":"/workspace/rust/crates/tools/src/lib.rs","diff":["@@ -0,0 +1,4469 @@"]},
    {"path":"/workspace/rust/docs/releases/0.1.0.md","diff":["@@ -0,0 +1,51 @@"]},
    {"path":"/workspace/src/QueryEngine.py","diff":["@@ -0,0 +1,19 @@"]},
    {"path":"/workspace/src/Tool.py","diff":["@@ -0,0 +1,15 @@"]},
    {"path":"/workspace/src/__init__.py","diff":["@@ -0,0 +1,29 @@"]},
    {"path":"/workspace/src/assistant/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/bootstrap/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/bootstrap_graph.py","diff":["@@ -0,0 +1,27 @@"]},
    {"path":"/workspace/src/bridge/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/buddy/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/cli/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/command_graph.py","diff":["@@ -0,0 +1,34 @@"]},
    {"path":"/workspace/src/commands.py","diff":["@@ -0,0 +1,90 @@"]},
    {"path":"/workspace/src/components/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/constants/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/context.py","diff":["@@ -0,0 +1,47 @@"]},
    {"path":"/workspace/src/coordinator/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/costHook.py","diff":["@@ -0,0 +1,8 @@"]},
    {"path":"/workspace/src/cost_tracker.py","diff":["@@ -0,0 +1,13 @@"]},
    {"path":"/workspace/src/deferred_init.py","diff":["@@ -0,0 +1,31 @@"]},
    {"path":"/workspace/src/dialogLaunchers.py","diff":["@@ -0,0 +1,15 @@"]},
    {"path":"/workspace/src/direct_modes.py","diff":["@@ -0,0 +1,21 @@"]},
    {"path":"/workspace/src/entrypoints/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/execution_registry.py","diff":["@@ -0,0 +1,51 @@"]},
    {"path":"/workspace/src/history.py","diff":["@@ -0,0 +1,22 @@"]},
    {"path":"/workspace/src/hooks/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/ink.py","diff":["@@ -0,0 +1,6 @@"]},
    {"path":"/workspace/src/interactiveHelpers.py","diff":["@@ -0,0 +1,5 @@"]},
    {"path":"/workspace/src/keybindings/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/main.py","diff":["@@ -0,0 +1,213 @@"]},
    {"path":"/workspace/src/memdir/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/migrations/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/models.py","diff":["@@ -0,0 +1,49 @@"]},
    {"path":"/workspace/src/moreright/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/native_ts/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/outputStyles/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/parity_audit.py","diff":["@@ -0,0 +1,138 @@"]},
    {"path":"/workspace/src/permissions.py","diff":["@@ -0,0 +1,20 @@"]},
    {"path":"/workspace/src/plugins/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/port_manifest.py","diff":["@@ -0,0 +1,52 @@"]},
    {"path":"/workspace/src/prefetch.py","diff":["@@ -0,0 +1,23 @@"]},
    {"path":"/workspace/src/projectOnboardingState.py","diff":["@@ -0,0 +1,10 @@"]},
    {"path":"/workspace/src/query.py","diff":["@@ -0,0 +1,13 @@"]},
    {"path":"/workspace/src/query_engine.py","diff":["@@ -0,0 +1,193 @@"]},
    {"path":"/workspace/src/reference_data/__init__.py","diff":["@@ -0,0 +1 @@"]},
    {"path":"/workspace/src/reference_data/archive_surface_snapshot.json","diff":["@@ -0,0 +1,63 @@"]},
    {"path":"/workspace/src/reference_data/commands_snapshot.json","diff":["@@ -0,0 +1,1037 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/assistant.json","diff":["@@ -0,0 +1,8 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/bootstrap.json","diff":["@@ -0,0 +1,8 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/bridge.json","diff":["@@ -0,0 +1,32 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/buddy.json","diff":["@@ -0,0 +1,13 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/cli.json","diff":["@@ -0,0 +1,26 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/components.json","diff":["@@ -0,0 +1,32 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/constants.json","diff":["@@ -0,0 +1,28 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/coordinator.json","diff":["@@ -0,0 +1,8 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/entrypoints.json","diff":["@@ -0,0 +1,15 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/hooks.json","diff":["@@ -0,0 +1,32 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/keybindings.json","diff":["@@ -0,0 +1,21 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/memdir.json","diff":["@@ -0,0 +1,15 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/migrations.json","diff":["@@ -0,0 +1,18 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/moreright.json","diff":["@@ -0,0 +1,8 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/native_ts.json","diff":["@@ -0,0 +1,11 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/outputStyles.json","diff":["@@ -0,0 +1,8 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/plugins.json","diff":["@@ -0,0 +1,9 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/remote.json","diff":["@@ -0,0 +1,11 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/schemas.json","diff":["@@ -0,0 +1,8 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/screens.json","diff":["@@ -0,0 +1,10 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/server.json","diff":["@@ -0,0 +1,10 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/services.json","diff":["@@ -0,0 +1,32 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/skills.json","diff":["@@ -0,0 +1,27 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/state.json","diff":["@@ -0,0 +1,13 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/types.json","diff":["@@ -0,0 +1,18 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/upstreamproxy.json","diff":["@@ -0,0 +1,9 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/utils.json","diff":["@@ -0,0 +1,32 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/vim.json","diff":["@@ -0,0 +1,12 @@"]},
    {"path":"/workspace/src/reference_data/subsystems/voice.json","diff":["@@ -0,0 +1,8 @@"]},
    {"path":"/workspace/src/reference_data/tools_snapshot.json","diff":["@@ -0,0 +1,922 @@"]},
    {"path":"/workspace/src/remote/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/remote_runtime.py","diff":["@@ -0,0 +1,25 @@"]},
    {"path":"/workspace/src/replLauncher.py","diff":["@@ -0,0 +1,5 @@"]},
    {"path":"/workspace/src/runtime.py","diff":["@@ -0,0 +1,192 @@"]},
    {"path":"/workspace/src/schemas/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/screens/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/server/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/services/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/session_store.py","diff":["@@ -0,0 +1,35 @@"]},
    {"path":"/workspace/src/setup.py","diff":["@@ -0,0 +1,77 @@"]},
    {"path":"/workspace/src/skills/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/state/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/system_init.py","diff":["@@ -0,0 +1,23 @@"]},
    {"path":"/workspace/src/task.py","diff":["@@ -0,0 +1,5 @@"]},
    {"path":"/workspace/src/tasks.py","diff":["@@ -0,0 +1,11 @@"]},
    {"path":"/workspace/src/tool_pool.py","diff":["@@ -0,0 +1,37 @@"]},
    {"path":"/workspace/src/tools.py","diff":["@@ -0,0 +1,96 @@"]},
    {"path":"/workspace/src/transcript.py","diff":["@@ -0,0 +1,23 @@"]},
    {"path":"/workspace/src/types/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/upstreamproxy/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/utils/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/vim/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/src/voice/__init__.py","diff":["@@ -0,0 +1,16 @@"]},
    {"path":"/workspace/tests/test_porting_workspace.py","diff":["@@ -0,0 +1,248 @@"]}
]

print("此次合并引入了重大更新，主要引入了项目核心功能的 Rust 语言重构版本（包括 API 客户端、运行时、CLI 工具和插件系统等），并新增了配套的 Python 源代码、子系统配置数据以及测试文件。这些更改旨在提供一个更快、更内存安全的运行环境，同时全面更新了项目的文档和资源文件。")
print("| 文件 | 变更 |")
print("|------|---------|")
for item in data:
    path = item["path"].replace("/workspace/", "")
    if path == "README.md":
        change = "- 重写文件内容，更新了项目的最新介绍和 Rust 移植进度"
    elif "diff" in item and not item["diff"]:
        change = "- 新增了该文件"
    else:
        change = "- 新增了该文件"
    print(f"| {path} | {change} |")

